# XML example and exercise
****
+ study examples of accessing nodes in XML tree structure  
+ work on exercise to be completed and submitted
****
+ reference: https://docs.python.org/2.7/library/xml.etree.elementtree.html
+ data source: http://www.dbis.informatik.uni-goettingen.de/Mondial
****

In [2]:
from xml.etree import ElementTree as ET
import pandas as pd

## XML example

+ for details about tree traversal and iterators, see https://docs.python.org/2.7/library/xml.etree.elementtree.html

In [2]:
document_tree = ET.parse( './data/mondial_database_less.xml' )

In [5]:
# print names of all countries
for child in document_tree.getroot():
    print(child.find('name').text)

Albania
Greece
Macedonia
Serbia
Montenegro
Kosovo
Andorra

In [6]:
# print names of all countries and their cities
for element in document_tree.iterfind('country'):
    print('* ' + element.find('name').text + ':',)
    capitals_string = ''
    for subelement in element.getiterator('city'):
        capitals_string += subelement.find('name').text + ', '
    print(capitals_string[:-2])

* Albania:
Tirana, Shkodër, Durrës, Vlorë, Elbasan, Korçë
* Greece:
Komotini, Kavala, Athina, Peiraias, Peristeri, Acharnes, Patra, Kozani, Kerkyra, Ioannina, Thessaloniki, Iraklio, Chania, Ermoupoli, Rhodes, Tripoli, Lamia, Chalkida, Larissa, Volos, Mytilini, Karyes
* Macedonia:
Skopje, Kumanovo
* Serbia:
Beograd, Novi Sad, Niš
* Montenegro:
Podgorica
* Kosovo:
Prishtine
* Andorra:
Andorra la Vella

****
## XML exercise

Using data in 'data/mondial_database.xml', the examples above, and refering to https://docs.python.org/2.7/library/xml.etree.elementtree.html, find

1. 10 countries with the lowest infant mortality rates
2. 10 cities with the largest population
3. 10 ethnic groups with the largest overall populations (sum of best/latest estimates over all countries)
4. name and country of a) longest river, b) largest lake and c) airport at highest elevation

In [3]:
document = ET.parse( './data/mondial_database.xml' )
root = document.getroot()

In [19]:
# print names of all countries
for child in root:
    print(child.find('name').text)

Albania
Greece
Macedonia
Serbia
Montenegro
Kosovo
Andorra
France
Spain
Austria
Czech Republic
Germany
Hungary
Italy
Liechtenstein
Slovakia
Slovenia
Switzerland
Belarus
Latvia
Lithuania
Poland
Ukraine
Russia
Belgium
Luxembourg
Netherlands
Bosnia and Herzegovina
Croatia
Bulgaria
Romania
Turkey
Denmark
Estonia
Faroe Islands
Finland
Norway
Sweden
Monaco
Gibraltar
Guernsey
Holy See
Ceuta
Melilla
Iceland
Ireland
San Marino
Jersey
Malta
Isle of Man
Moldova
Portugal
Svalbard
United Kingdom
Afghanistan
China
Iran
Pakistan
Tajikistan
Turkmenistan
Uzbekistan
Armenia
Georgia
Azerbaijan
Bahrain
Bangladesh
Myanmar
India
Bhutan
Brunei
Malaysia
Laos
Thailand
Cambodia
Vietnam
Kazakhstan
North Korea
Kyrgyzstan
Hong Kong
Macao
Mongolia
Nepal
Christmas Island
Cocos Islands
Cyprus
Gaza Strip
Israel
Egypt
Indonesia
Timor-Leste
Papua New Guinea
Iraq
Jordan
Kuwait
Saudi Arabia
Syria
Lebanon
West Bank
Japan
South Korea
Maldives
Oman
United Arab Emirates
Yemen
Philippines
Qatar
Singapore
Sri Lanka
Taiwan
Anguilla
Antigua and Barbuda
Aruba
Bahamas
Barbados
Belize
Guatemala
Mexico
Bermuda
British Virgin Islands
Canada
United States
Cayman Islands
Costa Rica
Nicaragua
Panama
Cuba
Dominica
Dominican Republic
Haiti
El Salvador
Honduras
Greenland
Grenada
Guadeloupe
Jamaica
Martinique
Montserrat
Curacao
Sint Maarten
Saint Martin
Saint Barthelemy
Colombia
Puerto Rico
Saint Kitts and Nevis
Saint Lucia
Saint Pierre and Miquelon
Saint Vincent and the Grenadines
Trinidad and Tobago
Turks and Caicos Islands
Virgin Islands
American Samoa
Australia
Cook Islands
Fiji
French Polynesia
Guam
Kiribati
Marshall Islands
Micronesia
Nauru
New Caledonia
New Zealand
Niue
Norfolk Island
Northern Mariana Islands
Palau
Pitcairn
Solomon Islands
Tonga
Tuvalu
Tokelau
Vanuatu
Wallis and Futuna
Samoa
Argentina
Bolivia
Brazil
Chile
Paraguay
Uruguay
Peru
French Guiana
Guyana
Suriname
Venezuela
Ecuador
Falkland Islands
Algeria
Libya
Mali
Mauritania
Morocco
Niger
Tunisia
Western Sahara
Angola
Congo
Namibia
Zaire
Zambia
Benin
Burkina Faso
Nigeria
Togo
Botswana
South Africa
Zimbabwe
Cote dIvoire
Ghana
Burundi
Rwanda
Tanzania
Cameroon
Central African Republic
Chad
Equatorial Guinea
Gabon
Cape Verde
Sudan
South Sudan
Comoros
Guinea
Liberia
Djibouti
Eritrea
Ethiopia
Somalia
Kenya
Gambia
Senegal
Guinea-Bissau
Sierra Leone
Uganda
Lesotho
Madagascar
Malawi
Mozambique
Mauritius
Mayotte
Swaziland
Reunion
Saint Helena
Sao Tome and Principe
Seychelles
Europe
Asia
Australia/Oceania
Africa
America
African Development Bank Group
African Union
African Union/United Nations Hybrid Operation in Darfur
African, Caribbean, and Pacific Group of States
Agency for the Prohibition of Nuclear Weapons in Latin America and the Caribbean
Alliance of Small Island States
Andean Community
Arab Bank for Economic Development in Africa
Arab Fund for Economic and Social Development
Arab Maghreb Union
Arab Monetary Fund
ASEAN Regional Forum
Asia-Pacific Economic Cooperation
Asian Development Bank
Association of Southeast Asian Nations
Australia Group
Australia-New Zealand-United States Security Treaty
Baltic Assembly
Bank for International Settlements
Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation
Benelux Union
Black Sea Economic Cooperation Zone
Caribbean Community and Common Market
Caribbean Development Bank
Central African States Development Bank
Central American Bank for Economic Integration
Central American Common Market
Central American Integration System
Central European Initiative
Collective Security Treaty Organization
Colombo Plan
Common Market for Eastern and Southern Africa
Commonwealth
Commonwealth of Independent States
Community of Democracies
Community of Latin American and Caribbean States
Comuinidade dos Paises de Lingua Portuguesa
Conference of Interaction and Confidence-Building Measures in Asia
Council of Arab Economic Unity
Convention of the Southeast European Law Enforcement Center
Council of Europe
Council of the Baltic Sea States
Council of the Entente
Developing Eight
East African Community
East African Development Bank
East Asia Summit
Economic and Monetary Community of Central Africa
Economic and Monetary Union
Economic Community of the Great Lakes Countries
Economic Community of West African States
Economic Cooperation Organization
Eurasian Economic Community
Euro-Atlantic Partnership Council
European Bank for Reconstruction and Development
European Central Bank
European Free Trade Association
European Investment Bank
European Organization for Nuclear Research
European Space Agency
European Union
Extractive Industry Transparency Initiative
Financial Action Task Force
Food and Agriculture Organization
Franc Zone
General Confederation of Trade Unions
Group of 10
Group of 11
Group of 15
Group of 20
Group of 24
Group of 3
Group of 5
Group of 7
Group of 77
Group of 8
Group of 9
Gulf Cooperation Council
Indian Ocean Commission
Inter-American Development Bank
Inter-Governmental Authority on Development
Inter-Parliamentary Union
International Atomic Energy Agency
International Bank for Reconstruction and Development
International Chamber of Commerce
International Civil Aviation Organization
International Court of Justice
International Criminal Court
International Criminal Police Organization
International Development Association
International Energy Agency
International Federation of Red Cross and Red Crescent Societies
International Finance Corporation
International Fund for Agricultural Development
International Hydrographic Organization
International Labor Organization
International Maritime Organization
International Mobile Satellite Organization
International Monetary Fund
International Olympic Committee
International Organization for Migration
International Organization for Standardization
International Organization of the French-speaking World
International Telecommunication Satellite Organization
International Telecommunication Union
International Trade Union Confederation
Islamic Development Bank
Latin American and Caribbean Economic System
Latin American Integration Association
League of Arab States
Multilateral Investment Guarantee Agency
Nonaligned Movement
Nordic Council
Nordic Investment Bank
North American Free Trade Agreement
North Atlantic Treaty Organization
Nuclear Energy Agency
Nuclear Suppliers Group
Organization for Democracy and Economic Development
Organization for Economic Cooperation and Development
Organization for Security and Cooperation in Europe
Organization for the Prohibition of Chemical Weapons
Organization of American States
Organization of Arab Petroleum Exporting Countries
Organization of Eastern Caribbean States
Organization of Islamic Cooperation
Organization of Petroleum Exporting Countries
Pacific Islands Forum
Partnership for Peace
Permanent Court of Arbitration
Secretariat of the Pacific Community
Shanghai Cooperation Organization
South Asia Co-operative Environment Program
South Asian Association for Regional Cooperation
South Pacific Regional Trade and Economic Cooperation Agreement
Southern African Customs Union
Southern African Development Community
Southern Cone Common Market
Union of South American Nations
United Nations
United Nations Conference on Trade and Development
United Nations Disengagement Observer Force
United Nations Educational, Scientific, and Cultural Organization
United Nations High Commissioner for Refugees
United Nations Industrial Development Organization
United Nations Institute for Training and Research
United Nations Integrated Mission in Timor-Leste
United Nations Interim Force in Lebanon
United Nations Interim Security Force for Abyei
United Nations Military Observer Group in India and Pakistan
United Nations Mission for the Referendum in Western Sahara
United Nations Mission in Liberia
United Nations Mission in the Republic of South Sudan
United Nations Operation in Cote d'Ivoire
United Nations Organization Stabilization Mission in the Democratic Republic of the Congo
United Nations Peacekeeping Force in Cyprus
United Nations Relief and Works Agency for Palestine Refugees in the Near East
United Nations Security Council
United Nations Truce Supervision Organization
Universal Postal Union
World Customs Organization
World Federation of Trade Unions
World Health Organization
World Intellectual Property Organization
World Meteorological Organization
World Tourism Organization
World Trade Organization
Zangger Committee
Atlantic Ocean
Mediterranean Sea
Black Sea
Marmara Sea
Sea of Azov
The Channel
Irish Sea
North Sea
Skagerrak
Kattegat
Baltic Sea
Norwegian Sea
Greenland Sea
Barents Sea
Kara Sea
Arctic Ocean
East Sibirian Sea
Bering Sea
Hudson Bay
Labrador Sea
Gulf of Mexico
Caribbean Sea
Pacific Ocean
Sea of Okhotsk
Sea of Japan
Yellow Sea
East China Sea
South China Sea
Indian Ocean
Arabian Sea
Gulf of Oman
Persian Gulf
Red Sea
Gulf of Aden
Gulf of Bengal
Andaman Sea
Malakka Strait
Java Sea
Banda Sea
Sulawesi Sea
Sulu Sea
Thjorsa
Joekulsa a Fjoellum
Glomma
Lagen
Goetaaelv
Klaraelv
Umeaelv
Dalaelv
Vaesterdalaelv
Oesterdalaelv
Paatsjoki
Ounasjoki
Kemijoki
Oulujoki
Kymijoki
Kokemaeenjoki
Vuoksi
Thames
Maas
Loire
Garonne
Rhone
Saone
Doubs
Isere
Seine
Marne
Tajo
Douro
Guadiana
Guadalquivir
Ebro
Po
Ticino
Adda
Mincio
Etsch
Tiber
Arno
Donau
Breg
Brigach
Iller
Lech
Isar
Ammer
Würm
Inn
Alz
Salzach
Enns
March
Raab
Waag
Drau
Mur
Theiss
Save
Drina
Tara
Piva
Morava
Western Morava
Southern Morava
Olt
Pruth
Dnjestr
Weser
Aller
Leine
Werra
Fulda
Elbe
Moldau
Rhein
Main
Mosel
Saar
Neckar
Aare
Reuss
Limmat
Oder
Weichsel
Narew
Western Bug
Moraca
Buna
Drin
White Drin
Black Drin
Jordan
Kura
Schatt al Arab
Tigris
Euphrat
Murat
Karasu
Karun
Northern Dwina
Suchona
Petschora
Newa
Swir
Narva
Western Dwina
Dnister
Dnepr
Prypjat
Don
Volga
Oka
Kama
Ural
Ob
Irtysch
Tobol
Ischim
Katun
Jenissej
Angara
Selenge
Chatanga
Lena
Amur
Schilka
Argun
Kolyma
Syrdarja
Naryn
Amudarja
Pjandsh
Bartang
Murgab
Ili
Tarim-Yarkend
Hwangho
Jangtse
Mekong
Saluen
Irawaddy
Ganges
Brahmaputra
Indus
Asahan
Yukon River
Mackenzie River
Nelson River
Saskatchewan River
Saint Lawrence River
Niagara River
Detroit River
Saint Marys River
Straits of Mackinac
Manicouagan
Riviere Richelieu
Merrimack River
Connecticut River
Hudson River
Mississippi
Missouri
Arkansas
Ohio River
Allegheny River
Tennessee
Columbia River
Truckee River
Colorado
Rio Grande
Rio Lerma
Rio San Juan
Rio Desaguadero
Rio Magdalena
Orinoco
Amazonas
Rio Negro
Rio Madeira
Rio Mamore
Tocantins
Rio Sao Francisco
Parana
Paraguay
Uruguay
Gambia
Senegal
Volta
Niger
Bani
Benue
Schari
Nile
Atbara
Blue Nile
White Nile
Sobat
Pibor
Baro
Bahr el-Ghasal
Bahr el-Djebel/Albert-Nil
Semliki
Victoria Nile
Akagera
Jubba
Shabelle
Sanaga
Zaire
Sanga
Ubangi
Bomu
Uelle
Kwa
Fimi
Lukenie
Kasai
Cuango
Cuilo
Ruki
Busira
Tshuapa
Lulua
Lomami
Aruwimi
Lualaba
Lukuga
Ruzizi
Luvua
Luapula
Zambezi
Chire
Okavango
Limpopo
Oranje
Vaal
Murray River
Darling River
Murrumbidgee River
Eucumbene River
Snowy River
Inari
Oulujaervi
Kallavesi
Saimaa
Paeijaenne
Mjoesa-See
Storuman
Siljan
Maelaren
Vaenern
Vaettern
Arresoe
Loch Ness
Loch Lomond
Bodensee
Chiemsee
Starnberger See
Ammersee
Laacher Maar
Lac Leman
Zurichsee
Thunersee
Brienzersee
Vierwaldstattersee
Lago Maggiore
Lago di Como
Lago di Garda
Lago Trasimeno
Lago di Bolsena
Lago di Bracciano
Laguna de Gallocanta
Neusiedlersee
Balaton
Lake Skutari
Lake Prespa
Lake Ohrid
Kiev Reservoir
Kakhovka Reservoir
Kremenchuk Reservoir
Kuybyshev Reservoir
Ozero Ladoga
Ozero Onega
Ozero Pskovskoje
Ozero Baikal
Ozero Taimyr
Ozero Chanka
Ozero Tschany
Dead Sea
Lake Genezareth
Lake Van
Lake Keban
Lake Urmia
Daryacheh ye Namak
Hamun e Jaz Murian
Caspian Sea
Ozero Aral
Ozero Balchash
Issyk-Kul
Koli Sarez
Lop Nor
Laguna de Bay
Lake Toba
Segara Anak
Qinghai Lake
Nam Co
Lake Nasser
Lake Volta
Lake Bosumtwi
Lake Kainji
Chad Lake
Barrage de Mbakaou
Lake Nyos
Lac Assal
Lake Abbe
Lake Abaya
Chew Bahir
Lake Turkana
Lake Tana
Lake Sese Seko/Albertsee
Rutanzige/Eduardsee
Lake Kioga
Lake Victoria
Lake Kivu
Lake Tanganjika
Lake Mweru
Lake Bangweulu
Lake Rukwa
Lake Eyasi
Lake Natron
Lake Malawi
Lake Chilwa
Lake Mai Ndombe
Malebo Pool
Lake Cabora-Bassa
Lake Kariba
Lake Ngami
Etoscha Salt Pan
Makarikari Salt Pan
Great Bear Lake
Great Slave Lake
Atlin Lake
Lake Winnipeg
Lake Nipigon
Lake Manicouagan
Lake Ontario
Lake Erie
Lake Huron
Lake Manitou
Lake Michigan
Lake Superior
Lake Champlain
Lake Winnipesaukee
Lake Okeechobee
Kentucky Lake
Chickamauga Lake
Franklin. D. Roosevelt Lake
Crater Lake
Great Salt Lake
Lake Tahoe
Pyramid Lake
Lake Powell
Lake Mead
Fort Peck Lake
Lake Sakakawea
Lake Oahe
Lago de Chapala
Lake Nicaragua
Lake Managua
Lake Irazu
Lake Maracaibo
Lago de Sobradinho
Lake Titicaca
Poopo
Salar de Uyuni
Licancabur Crater Lake
Laguna Mar Chiquita
Lake Eyre
Lake Burley Griffin
Lake Eucumbene
Lake Jindabyne
Lake Hume
Svalbard
Greenland
Iceland
Aust-Vagoey
Streymoy
Ireland
Great Britain
Shetland Mainland
Orkney Mainland
South Ronaldsay
Hoy
Westray
Barra
South Uist
Benbecula
North Uist
Lewis and Harris
Skye
Rhum
Mull
Tiree
Islay
Jura
Arran
Isle of Man
Anglesey
Isle of Wight
Bishop Rock
Guernsey
Jersey
Gotland
Oeland
Aland
Dagoe
Oesel
Seeland
Fuenen
Langeland
Falster
Lolland
Bornholm
Fehmarn
Rugen
Usedom
Helgoland
Sylt
Fohr
Amrum
Pellworm
Wangerooge
Spiekeroog
Langeoog
Baltrum
Norderney
Juist
Borkum
Schiermonnikoog
Ameland
Terschelling
Vlieland
Texel
Zitny Ostrov
Maly Zitny Ostrov
Margit Sziget
Veliki Ratno Ostrvo
Korfu
Lefkas
Kefallinia
Zakynthos
Kreta
Chios
Samos
Ikaria
Lesbos
Kos
Rhodos
Syros
Mykonos
Cyprus
Alicudi
Filicudi
Salina
Lipari
Vulcano
Panarea
Stromboli
Lampedusa
Linosa
Sicilia
Malta
Gozo
Sardegna
Corse
Menorca
Mallorca
Ibiza
Formentera
Lanzarote
Fuerteventura
Gran Canaria
Teneriffa
Gomera
Hierro
La Palma
Madeira
Porto Santo
Sao Miguel
Santa Maria
Terceira
Sao Jorge
Pico
Faial
Graciosa
Flores
Corvo
Santiago
Fogo
Sao Tome
Principe
Bioko
Saint Helena
Ascension
Tristan Da Cunha
West Falkland
East Falkland
Bahrain
Khark
Gheschm
Lavan
Christmas Island
Pulau Panjang
Male
Kavaratti
Sri Lanka
South Andaman Island
Sokotra
Sansibar
Pemba
Mahe
Grand Comoro
Anjouan
Mohilla
Mayotte
Reunion
Mauritius
Madagaskar
Nowaja Semlja
Kotelny Island
Paramuschir
Olkhon
Sachalin
Hokkaido
Kyushu
Shikoku
Honshu
Okinawa
Jeju
Taiwan
Hainan
Zhoushan
Luzon
Mindoro
Negros
Panay
Bohol
Leyte
Samar
Cebu
Mindanao
Palawan
Singapore
Ko Samui
Phuket
Sumatra
Samosir
Batam
Bintan
Bangka
Krakatau
Java
Borneo
Labuan
Bali
Lombok
Sumbawa
Sulawesi
Timor
Ambon
Ceram
Halmahera
Ternate
New Guinea
Bougainville
Guadalcanal
Grande Terre
Cangaroo Island
Melville Island
Tasmania
Victoria Island
Banks Island
Prince of Wales Island
Baffin Island
Southampton Island
Ellesmere Island
Devon Island
Saint Pierre
Miquelon-Langlade
Newfoundland
Prince Edward Island
Rene Levasseur Island
Manitoulin
Marthas Vineyard
Nantucket
Long Island
Grand Bermuda
New Providence
Grand Turk
Providenciales
North Caicos
Cuba
Jamaica
Hispaniola
Puerto Rico
Tortola
Saint Thomas
Anguilla
St. Martin
St. Barthelemy
Saint Kitts
Nevis
Barbuda
Antigua
Montserrat
Basse-Terre
Grande-Terre
Dominica
Martinique
Saint Lucia
Saint Vincent
Barbados
Grenada
Trinidad
Tobago
Curacao
Aruba
Grand Cayman
Little Cayman
Cayman Brac
San Andres
Isla da Ometepe
Unalaska
Vancouver Island
Santa Cruz Island
Santa Catalina Island
Santa Rosa Island
San Clemente Island
San Miguel Island
Isabela
Niihau
Kauai
Oahu
Molokai
Lanai
Maui
Hawaii
Niue
Saipan
Tinian
Rota
Uvea
Futuna
Tarawa
Kiritimati
Banaba
Tongatapu
Viti Levu
Vanua Levu
Norfolk Island
Nauru
Koror
Babelthuap
Fongafale
Fakaofo
Efate
Upolu
Savaii
Tutuila
Rarotonga
Tahiti
Guam
Majuro
Ponape
Pitcairn
Easter Island
Te Ika-a-Maui (North Island)
Te Waka-a-Maui (South Island)
Hvannadalshnukur
Snaefell
Hekla
Katla
Haltiatunturi
Kebnekaise
Sarektjokko
Portefjaellen
Tarrekaise
Sulitjelma
Galdhoeppig
Jostedalsbre
Glittertind
Joekul
Snoehetta
Ben Nevis
Feldberg
Brocken
Grosser Arber
Zugspitze
Mont Blanc
Barre des Ecrins
Grand Combin
Matterhorn
Monte Rosa
Finsteraarhorn
Gran Paradiso
Piz Bernina
Crap Sogn Gion
Marmolata
Grossglockner
Hochgolling
Grand Ballon
Puy De Dome
Puy de Sancy
Vignemale
Pico de Aneto
Torre de Cerredo
Pico de Almanzor
Moncayo
Mulhacen
Torre de Estrela
Monte Cinto
Gran Sasso
Monte Falterona
Vesuv
Etna
Schneekoppe
Gerlachovsky Stit
Moldoveanu
Musala
Jezerce
Korab
Olymp
Athos
Psiloritis
Olympos
Pico de Teide
Pico de los Nieves
Roque de los Muchachos
Pico Ruivo
Pico
Fogo
Tubkhal
Djebel Aures
Tahat
Tamgak
Mont Greboun
Emi Kussi
Jabal Marra
Jabal Katrina
Aso Rock
Fako
Pico Basile
Pico de Sao Tome
Queen Marys Peak
Ras Daschan Terara
Ruwenzori
Elgon
Mount Kenia
Kilimanjaro
Mawenzi
Meru
Karisimbi
Thabana Ntlenyana
Cathkin Peak
Tsaratanana
Tsiafajavona
Andringitra
Piton des Neiges
Piton de la Fournaise
Karthala
Roman Kosch
Narodnaja
Demirkazik
Ararat
Jabal Lubnan
Elbrus
Dychtau
Schchara
Kasbek
Zachwoa
Damavand
Sabalan
Zard Kuh
Jabal Shuayb
Dodabetta
Pidurutalagala
Zhima
Bjelucha
Pik Chan-Tengri
Pik Pobeda
Liushi Shan
Ulug Muztag
Kongur
Muztagata
Pik Ismoil Somoni
Pik Lenina
Pik Revoluzija
Pik Moskva
Pik Karl-Marx
Tirich Mir
K2
Broad Peak
Gasherbrum I
Gasherbrum II
Nanga Parbat
Nanda Devi
Dhaulagiri
Annapurna
Manaslu
Shishapangma
Kailash
Cho Oyu
Mount Everest
Lhotse
Makalu
Kangchendzonga
Kljutschewskaja Sopka
Changbai Shan
Asahi-Dake
Fujisan
Hotaka-Dake
Yu Shan
Pulog
Pinatubo
Mount Apo
Kanlaon
Mantalingajan
Kinabalu
Tahan
Leuser
Kerinci
Krakatau
Merapi
Semeru
Gunung Agung
Rinjani
Tambora
Rantekombola
Tatamailau
Gunung Binaiya
Puncak Jaya
Mt. Wilhelm
Mt. Giluwe
Mt. Balbi
Mt. Victoria
Silisili
Mont Orohena
Popomanaseu
Mauna Kea
Mauna Loa
Haleakala
Mt. Kosciuszko
Mt. Bogong
Uluru
Mt. Cook
Ruapehu
Mt Redoubt
Mt McKinley
Mt Blackburn
Mt Bona
Mt St.Elias
Mt Logan
Mt Fairweather
Mt Waddington
Mt Robson
Mt Columbia
Barbeau Peak
Mt. Odin
Mt. Babel
Granite Peak
Borah Peak
Harney Peak
Gannett Peak
Kings Peak
Mt Elbert
Pikes Peak
Wheeler Peak
Humphreys Peak
Guadalupe Peak
Mt Rainier
Mt Adams
Mt Hood
Mt Whitney
Boundary Peak
Mt Washington
Mt Marcy
Mt Mitchell
Clingmans Dome
Citlaltepetl (Pico de Orizaba)
Popocatepetl
Iztaccihuatl
Nevado de Toluca
Nevado de Colima
Tajumulco
Concepcion
Irazu
Cerro Chirripo
Pico Turquino
Blue Mountain Peak
Pico Duarte
Cerro de Punta
La Soufriere
Soufriere Hills
Soufriere
Morne Diablotins
Pelee
Pico Cristobal Colon
Pico Bolivar
Nevado del Ruiz
Nevado del Huila
Cayambe
Cotopaxi
Chimborazo
Huascaran
Alpamayo
Pico Rocarre
Ausangate
Coropuna
Ampato
Illampu
Illimani
Sajama
Licancabur
Llullaillaco
Ojos del Salado
Monte Pissis
Aconcagua
Tupungato
Pico de Agulhas Negras
Kalahari
Namib
Ferlo
Trarza
Erg Ouarane
Erg Maqteir
Saguia el-Hamra
Erg Igidi
Hamada du Draa
Erg Chech
Tanezrouft
Grand Erg Ouest
Grand Erg Est
Erg Isaouane
Hamada al-Hamra
Fesan
Erg Rebiana
Talak
Tenere
Djourab
Erdi Ennedi
Libyan Desert
Darfur
Arabian Desert
Nubian Desert
Negev
Syrian Desert
Nefud
Rub Al Chali
Dascht-e-Kavir
Dascht-e-Lut
Dascht-e-Margoh
Rigestan
Thar
Ryn
Ust Urt
Karakum
Kysylkum
Mujunkum
TaklaMakan
Gurbantunggut
Kum Tagh
Qaidam
Gobi
Ordos
Great Sandy Desert
Gibson Desert
Great Victoria Desert
Nullarbor Plain
Simpson Desert
Red Centre
Tanami
Sturt Desert
Owyhee
Great Salt Lake Desert
Colorado Plateau
Great Basin
Mojave
Sonora
Chihuahua
Baja California Desert
Atacama
Herat
Kabul Intl
Tirana Rinas
Cheikh Larbi Tebessi
Batna Airport
Soummam
Tamanrasset
Biskra
Mohamed Boudiaf Intl
Ain Arnat Airport
Es Senia
Noumerat
Annaba
Houari Boumediene
Zenata
Pago Pago Intl
Lubango
Cabinda
Menongue
Luanda 4 De Fevereiro
Huambo
Wallblake
V C Bird Intl
La Rioja
Jujuy
Comandante Espora
Teniente Benjamin Matienzo
San Luis
Santiago del Estero
Sauce Viejo
Corrientes
Presidente Peron
Salta
Aeroparque Jorge Newbery
Ministro Pistarini
Ushuaia Malvinas Argentinas
Formosa
Posadas
Rosario
Resistencia
Rio Gallegos
Comodoro Rivadavia
Mar Del Plata
El Plumerillo
Ambrosio L V Taravella
Zvartnots
Reina Beatrix Intl
Melbourne Intl
Sydney Intl
Cairns Intl
Townsville
Brisbane Intl
Canberra
Adelaide Intl
Newcastle Airport
Darwin Intl
Perth Intl
Hobart
Salzburg
Linz
Innsbruck
Schwechat
Graz

In [20]:
# 10 countries with the lowest infant mortality rates
# print infant mortality rates of each country
for element in document.iterfind('country'):
    if element.find('infant_mortality') != None:
        print('* ' + element.find('name').text + ':',)
        print(element.find('infant_mortality').text)

* Albania:
13.19
* Greece:
4.78
* Macedonia:
7.9
* Serbia:
6.16
* Andorra:
3.69
* France:
3.31
* Spain:
3.33
* Austria:
4.16
* Czech Republic:
2.63
* Germany:
3.46
* Hungary:
5.09
* Italy:
3.31
* Liechtenstein:
4.33
* Slovakia:
5.35
* Slovenia:
4.04
* Switzerland:
3.73
* Belarus:
3.64
* Latvia:
7.91
* Lithuania:
6
* Poland:
6.19
* Ukraine:
8.1
* Russia:
7.08
* Belgium:
4.18
* Luxembourg:
4.28
* Netherlands:
3.66
* Bosnia and Herzegovina:
5.84
* Croatia:
5.87
* Bulgaria:
15.08
* Romania:
10.16
* Turkey:
21.43
* Denmark:
4.1
* Estonia:
6.7
* Faroe Islands:
5.71
* Finland:
3.36
* Norway:
2.48
* Sweden:
2.6
* Monaco:
1.81
* Gibraltar:
6.29
* Guernsey:
3.47
* Iceland:
3.15
* Ireland:
3.74
* San Marino:
4.52
* Jersey:
3.86
* Malta:
3.59
* Isle of Man:
4.17
* Moldova:
12.93
* Portugal:
4.48
* United Kingdom:
4.44
* Afghanistan:
117.23
* China:
14.79
* Iran:
39
* Pakistan:
57.48
* Tajikistan:
35.03
* Turkmenistan:
38.13
* Uzbekistan:
19.84
* Armenia:
13.97
* Georgia:
16.68
* Azerbaijan:
26.67
* Bahrain:
9.68
* Bangladesh:
45.67
* Myanmar:
44.91
* India:
43.19
* Bhutan:
37.89
* Brunei:
10.48
* Malaysia:
13.69
* Laos:
54.53
* Thailand:
9.86
* Cambodia:
51.36
* Vietnam:
18.99
* Kazakhstan:
21.61
* North Korea:
24.5
* Kyrgyzstan:
28.71
* Hong Kong:
2.73
* Macao:
3.13
* Mongolia:
23.15
* Nepal:
40.43
* Cyprus:
8.54
* Gaza Strip:
30.6
* Israel:
3.98
* Egypt:
22.41
* Indonesia:
25.16
* Timor-Leste:
38.79
* Papua New Guinea:
39.67
* Iraq:
37.53
* Jordan:
15.73
* Kuwait:
7.51
* Saudi Arabia:
14.58
* Syria:
15.79
* Lebanon:
7.98
* West Bank:
28.6
* Japan:
2.13
* South Korea:
3.93
* Maldives:
24.59
* Oman:
14
* United Arab Emirates:
10.92
* Yemen:
50.41
* Philippines:
17.64
* Qatar:
6.42
* Singapore:
2.53
* Sri Lanka:
9.02
* Taiwan:
4.49
* Anguilla:
3.4
* Antigua and Barbuda:
13.29
* Aruba:
11.74
* Bahamas:
12.5
* Barbados:
10.93
* Belize:
20.31
* Guatemala:
23.51
* Mexico:
12.58
* Bermuda:
2.48
* British Virgin Islands:
13.45
* Canada:
4.71
* United States:
6.17
* Cayman Islands:
6.21
* Costa Rica:
8.7
* Nicaragua:
20.36
* Panama:
10.7
* Cuba:
4.7
* Dominica:
11.61
* Dominican Republic:
19.63
* Haiti:
49.43
* El Salvador:
18.44
* Honduras:
18.72
* Greenland:
9.42
* Grenada:
10.5
* Guadeloupe:
8.3
* Jamaica:
13.69
* Martinique:
7.1
* Montserrat:
13.66
* Sint Maarten:
9.05
* Colombia:
15.02
* Puerto Rico:
7.73
* Saint Kitts and Nevis:
8.98
* Saint Lucia:
11.75
* Saint Pierre and Miquelon:
6.95
* Saint Vincent and the Grenadines:
13.07
* Trinidad and Tobago:
24.82
* Turks and Caicos Islands:
10.97
* Virgin Islands:
6.79
* American Samoa:
8.92
* Australia:
4.43
* Cook Islands:
14.33
* Fiji:
10.2
* French Polynesia:
4.78
* Guam:
5.51
* Kiribati:
35.37
* Marshall Islands:
21.39
* Micronesia:
21.93
* Nauru:
8.21
* New Caledonia:
5.46
* New Zealand:
4.59
* Northern Mariana Islands:
5.5
* Palau:
11.46
* Solomon Islands:
16.17
* Tonga:
12.36
* Tuvalu:
31.69
* Vanuatu:
16.41
* Wallis and Futuna:
4.49
* Samoa:
20.5
* Argentina:
9.96
* Bolivia:
38.61
* Brazil:
19.21
* Chile:
7.02
* Paraguay:
20.75
* Uruguay:
8.97
* Peru:
20.21
* French Guiana:
14.6
* Guyana:
33.56
* Suriname:
27.07
* Venezuela:
19.33
* Ecuador:
17.93
* Algeria:
21.76
* Libya:
11.87
* Mali:
104.34
* Mauritania:
56.06
* Morocco:
24.52
* Niger:
86.27
* Tunisia:
23.19
* Western Sahara:
145.82
* Angola:
79.99
* Congo:
59.34
* Namibia:
45.64
* Zaire:
73.15
* Zambia:
66.62
* Benin:
57.09
* Burkina Faso:
76.8
* Nigeria:
74.09
* Togo:
46.73
* Botswana:
9.38
* South Africa:
41.61
* Zimbabwe:
26.55
* Cote dIvoire:
60.16
* Ghana:
38.52
* Burundi:
63.44
* Rwanda:
59.59
* Tanzania:
43.74
* Cameroon:
55.1
* Central African Republic:
92.86
* Chad:
90.3
* Equatorial Guinea:
71.12
* Gabon:
47.03
* Cape Verde:
24.28
* Sudan:
52.86
* South Sudan:
68.16
* Comoros:
65.31
* Guinea:
55.24
* Liberia:
69.19
* Djibouti:
50.2
* Eritrea:
38.44
* Ethiopia:
55.77
* Somalia:
100.14
* Kenya:
40.71
* Gambia:
65.74
* Senegal:
52.72
* Guinea-Bissau:
90.92
* Sierra Leone:
73.29
* Uganda:
60.82
* Lesotho:
50.48
* Madagascar:
44.88
* Malawi:
48.01
* Mozambique:
72.42
* Mauritius:
10.59
* Mayotte:
56.29
* Swaziland:
54.82
* Reunion:
7.5
* Saint Helena:
17.63
* Sao Tome and Principe:
49.16
* Seychelles:
10.77

In [21]:
# get infant mortality rates of each country
i = 0
c = pd.Series('')
m = pd.Series(0)
for element in document.iterfind('country'):
    if element.find('infant_mortality') != None:
        c[i] = element.find('name').text
        m[i] = float(element.find('infant_mortality').text)
        i += 1
i

228

In [6]:
c.head(10)

0           Albania
1            Greece
2         Macedonia
3            Serbia
4           Andorra
5            France
6             Spain
7           Austria
8    Czech Republic
9           Germany
dtype: object

In [7]:
m.head(10)

0    13.00
1     4.78
2     7.90
3     6.16
4     3.69
5     3.31
6     3.33
7     4.16
8     2.63
9     3.46
dtype: float64

In [22]:
# combine c and m to df
df = pd.concat((c,m), axis=1)

In [23]:
# rename columns and print 10 countries with the lowest infant mortality rates
df.columns = ['Country', 'Infant mortality rates']
df.sort_values(by='Infant mortality rates').head(10)

            Country  Infant mortality rates
36           Monaco                    1.81
90            Japan                    2.13
109         Bermuda                    2.48
34           Norway                    2.48
98        Singapore                    2.53
35           Sweden                    2.60
8    Czech Republic                    2.63
72        Hong Kong                    2.73
73            Macao                    3.13
39          Iceland                    3.15

In [35]:
# 10 cities with the largest population
i = 0
c = pd.Series('')
p = pd.Series(0)
for city in root.iter('city'):
    if city.find('population') != None:
        c[i] = city.find('name').text
        p[i] = 0
        for element in city.getiterator('population'):
            p[i] = float(city.find('population').text)
        i += 1
i

3050

In [36]:
c.head(10)

0       Tirana
1      Shkodër
2       Durrës
3        Vlorë
4      Elbasan
5        Korçë
6       Kavala
7       Athina
8     Peiraias
9    Peristeri
dtype: object

In [37]:
p.head(10)

0    192000
1     62000
2     60000
3     56000
4     53000
5     52000
6     56705
7    885737
8    196389
9    141971
dtype: int64

In [38]:
# combine c and p to df
df = pd.concat((c,p), axis=1)

In [39]:
# rename columns and print 10 cities with the largest population
df.columns = ['City', 'Population']
df.sort_values(by='Population', ascending=False).head(10)

                  City  Population
1763             Seoul    10229262
1421            Mumbai     9925891
2594         São Paulo     9412894
1629           Jakarta     8259266
1251          Shanghai     8205598
1942  Ciudad de México     8092449
443             Moskva     8010954
1725             Tokyo     7843000
1250           Beijing     7362426
1467             Delhi     7206704

In [44]:
# 10 ethnic groups with the largest overall populations (sum of best/latest estimates over all countries)
n = 0
e = pd.Series('')
p = pd.Series(0)
for country in root.findall('country'):
    for group in country.findall('ethnicgroup'):
        percent = float(group.get('percentage'))
        i = 0
        flag = 0
        for i in range(n):
            if (e[i] == group.text):
                p[i] += float(country.find('population').text)*percent/100
                flag = 1
            i += 1
        if (flag == 0):
            e[n] = group.text
            p[n] = float(country.find('population').text)*percent/100
            n += 1
n

280

In [45]:
# combine e and p to df
df = pd.concat((e,p), axis=1) 
df.head(10)

             0             1
0     Albanian  2.830814e+06
1        Greek  1.199821e+06
2   Macedonian  5.980602e+05
3      Turkish  1.364263e+07
4        Gypsy  2.183555e+04
5         Serb  6.074623e+06
6  Montenegrin  1.944669e+05
7    Hungarian  1.028843e+07
8         Roma  8.898014e+05
9      Bosniak  1.108824e+06

In [46]:
# rename columns and print 10 ethnic groups with the largest overall populations
df.columns = ['Ethnic group', 'Overall population']
df.sort_values(by='Overall population', ascending=False).head(10)

    Ethnic group  Overall population
80   Han Chinese        4.975551e+08
128     European        1.928658e+08
106   Indo-Aryan        1.716454e+08
33       Russian        9.275844e+07
16       African        8.632937e+07
139     Japanese        8.170627e+07
21        German        6.623219e+07
105    Dravidian        5.959908e+07
70       English        4.231499e+07
150      Mestizo        3.554233e+07

In [44]:
# name and country of a) longest river, b) largest lake and c) airport at highest elevation
i = 0
code = pd.Series('')
c = pd.Series('')
for country in root.findall('country'):
    code[i] = country.get('car_code')
    c[i] = country.find('name').text
    i += 1
dfc = pd.concat((code,c), axis=1) 
dfc.columns = ['code', 'country']
dfc.head(100)

    code                 country
0     AL                 Albania
1     GR                  Greece
2     MK               Macedonia
3    SRB                  Serbia
4    MNE              Montenegro
5    KOS                  Kosovo
6    AND                 Andorra
7      F                  France
8      E                   Spain
9      A                 Austria
10    CZ          Czech Republic
11     D                 Germany
12     H                 Hungary
13     I                   Italy
14    FL           Liechtenstein
15    SK                Slovakia
16   SLO                Slovenia
17    CH             Switzerland
18    BY                 Belarus
19    LV                  Latvia
20    LT               Lithuania
21    PL                  Poland
22    UA                 Ukraine
23     R                  Russia
24     B                 Belgium
25     L              Luxembourg
26    NL             Netherlands
27   BIH  Bosnia and Herzegovina
28    HR                 Croatia
29    BG                Bulgaria
..   ...                     ...
70   MAL                Malaysia
71   LAO                    Laos
72   THA                Thailand
73     K                Cambodia
74    VN                 Vietnam
75   KAZ              Kazakhstan
76   NOK             North Korea
77   KGZ              Kyrgyzstan
78  HONX               Hong Kong
79  MACX                   Macao
80   MNG                Mongolia
81   NEP                   Nepal
82  XMAS        Christmas Island
83  COCO           Cocos Islands
84    CY                  Cyprus
85  GAZA              Gaza Strip
86    IL                  Israel
87    ET                   Egypt
88    RI               Indonesia
89    TL             Timor-Leste
90   PNG        Papua New Guinea
91   IRQ                    Iraq
92   JOR                  Jordan
93   KWT                  Kuwait
94    SA            Saudi Arabia
95   SYR                   Syria
96    RL                 Lebanon
97  WEST               West Bank
98     J                   Japan
99   ROK             South Korea

[100 rows x 2 columns]

In [48]:
# name and country of a) longest river
i = 0
r = pd.Series('')
c = pd.Series('')
l = pd.Series(0)
for river in root.findall('river'):
    r[i] = river.find('name').text
    if river.find('length') != None:
        l[i] = float(river.find('length').text)
    else:
        l[i] = 0
    source = river.find('source')
    c[i] = source.get('country')
    i += 1
i

238

In [49]:
# combine r,c,l to df
df = pd.concat((r,c,l), axis=1) 
df.head(10)

                     0   1      2
0              Thjorsa  IS  230.0
1  Joekulsa a Fjoellum  IS  206.0
2               Glomma   N  604.0
3                Lagen   N  322.0
4            Goetaaelv   S   93.0
5             Klaraelv   N  460.0
6              Umeaelv   S  470.0
7              Dalaelv   S  520.0
8       Vaesterdalaelv   S  320.0
9        Oesterdalaelv   S  241.0

In [50]:
# rename columns and print name and country of longest river
df.columns = ['River', 'Country', 'Length']
df.sort_values(by='Length', ascending=False).head(10)

        River Country  Length
174  Amazonas      PE  6448.0
137   Jangtse      CN  6380.0
136   Hwangho      CN  4845.0
123      Lena       R  4400.0
205     Zaire     ZRE  4374.0
138    Mekong      CN  4350.0
115   Irtysch     KAZ  4248.0
186     Niger      RG  4184.0
160  Missouri     USA  4130.0
119  Jenissej       R  4092.0

In [18]:
# name and country of b) largest lake
i = 0
lk = pd.Series('')
c = pd.Series('')
a = pd.Series(0)
for lake in root.findall('lake'):
    lk[i] = lake.find('name').text
    if lake.find('area') != None:
        a[i] = float(lake.find('area').text)
    else:
        a[i] = 0
    locate = lake.find('located')
    if locate != None:
        c[i] = locate.get('country')
    i += 1
i

141

In [19]:
# combine lk,c,a to df
df = pd.concat((lk,c,a), axis=1) 
df.head(10)

            0   1       2
0       Inari  SF  1040.0
1  Oulujaervi  SF   928.0
2   Kallavesi  SF   472.0
3      Saimaa  SF  4370.0
4  Paeijaenne  SF  1118.0
5  Mjoesa-See   N   368.0
6    Storuman   S   173.0
7      Siljan   S   290.0
8    Maelaren   S  1140.0
9     Vaenern   S  5648.0

In [20]:
# rename columns and print name and country of largest lake
df.columns = ['Lake', 'Country', 'Area']
df.sort_values(by='Area', ascending=False).head(10)

                Lake Country      Area
54       Caspian Sea       R  386400.0
109    Lake Superior     CDN   82103.0
81     Lake Victoria     EAT   68870.0
106       Lake Huron     CDN   59600.0
108    Lake Michigan     USA   57800.0
47          Dead Sea      IL   41650.0
83   Lake Tanganjika     ZRE   32893.0
98   Great Bear Lake     CDN   31792.0
43      Ozero Baikal       R   31492.0
89       Lake Malawi     MOC   29600.0

In [25]:
# name and country of c) airport at highest elevation
i = 0
ap = pd.Series('')
c = pd.Series('')
el = pd.Series(0)
for airport in root.findall('airport'):
    ap[i] = airport.find('name').text
    if airport.find('elevation').text != None:
        el[i] = float(airport.find('elevation').text)
    else:
        el[i] = 0
    c[i] = airport.get('country')
    i += 1
i

1315

In [26]:
# combine ap,c,el to df
df = pd.concat((ap,c,el), axis=1) 
df.head(10)

                      0    1       2
0                 Herat  AFG   977.0
1            Kabul Intl  AFG  1792.0
2          Tirana Rinas   AL    38.0
3  Cheikh Larbi Tebessi   DZ   811.0
4         Batna Airport   DZ   822.0
5               Soummam   DZ     6.0
6           Tamanrasset   DZ  1377.0
7                Biskra   DZ    88.0
8  Mohamed Boudiaf Intl   DZ   691.0
9     Ain Arnat Airport   DZ  1024.0

In [27]:
# rename columns and print name and country of airport at highest elevation
df.columns = ['Airport', 'Country', 'Elevation']
df.sort_values(by='Elevation', ascending=False).head(10)

                                               Airport Country  Elevation
80                                        El Alto Intl     BOL     4063.0
219                                      Lhasa-Gonggar      CN     4005.0
241                                       Yushu Batang      CN     3963.0
813                                            Juliaca      PE     3827.0
815             Teniente Alejandro Velasco Astete Intl      PE     3311.0
82                            Juana Azurduy De Padilla     BOL     2905.0
334                                Mariscal Sucre Intl      EC     2813.0
805                Coronel Fap Alfredo Mendivil Duarte      PE     2719.0
807  Mayor General FAP Armando Revoredo Iglesias Ai...      PE     2677.0
692                Licenciado Adolfo Lopez Mateos Intl     MEX     2581.0